### PR TITLE
updated Blog and disqus

### PR DESCRIPTION
**Pull request by webuimaker**
Updated code for review.

### CODE REVIEW

**Comment by arshaw** [comment]
@webuimaker, thank you so much for this PR! I have not had time to run it yet. And my internet has been very bad, and it will be very bad again tomorrow, I'm sorry. I have some minor feedback:

- is the `permalink` setting in each post necessary? can we move it somewhere global, like the config?
- is the `dsq_thread_id` setting in each post necessary? when I write a new post, how do I know what it will be?
- can you remove the `category` from each post?
- can you write a new post, as an example? it will help teach me how to do it
- could you give all files 2-spaces for indentation?

Thank you! I will talk with you again on Monday night or Tuesday.

**Comment by webuimaker** [comment]
1 . done
2. its used for show number of comments in post.
3. Done
4. I have started update later 
5. can you please explain more ?

**Comment by arshaw** [comment]
hey @webuimaker, things are looking good. here are the final TODO items:

1. Instead of having the "Archive" area on the right sidebar be a list of ALL posts, can you make it only the next **3** posts? And remove any text about year/date. It should end up looking something like this: Screen Shot 2019-04-22 at 10 14 09 PM
2. In each post, remove unnecessary markup. for example html like `<div style="margin: 1em 0; text-align: left;">` should always be removed. text like `<h2 style="text-align: left;">something</h2>` can be converted to `## something`
3. Can you make sure ALL posts look like they do on the live site? Right now, they look very different. This will be a lot of manual work, I know. For example, make sure your jekyll-hosted page http://127.0.0.1:4000/blog/2019/03/v4-officially-released/ looks exactly like https://fullcalendar.io/blog/2019/03/v4-officially-released

Does that make sense?

**Comment by webuimaker** [comment]
Hi Adam,

I have updated as per your comments and also remove inline css, I tried to
same look if any comments please let me know.

and due to WordPress exported file that's why its post is not accurate in
markdown format.

**Pull request merged**
